### ISSUE TITLE
老哥好，现在这套东西还在使用吗，有更新吗？

### ISSUE THREAD

**Issue by grayguest** [Gomaxx/goma-virtualbox-extension#1]

**Comment by grayguest** [comment]
测了一下，在Linux Mint 19.3上面还挺好用的，可能需要更改一下：
比如通知频率

**Comment by Gomaxx** [comment]
没再更新，自己一直在用

**Comment by grayguest** [comment]
好嘞，我打算改一下通知频率，这么一直弹会积压很多消息。

**Comment by grayguest** [comment]
@Gomaxx 老哥，再问一下，这个程序可以用在VMware上面吗？

**Comment by grayguest** [comment]
> @Gomaxx 老哥，再问一下，这个程序可以用在VMware上面吗？

自问自答，可以的，多谢老哥的程序。
